### ISSUE TITLE
2012 and 2015 players loop back around if the video has chapters, the bar extends beyond the player if not

### ISSUE THREAD

**Issue by lovebug0706** [lightbeam24/CustomTube#103]
Title says it all. I recorded it, and took an image of it.

https://github.com/lightbeam24/CustomTube/assets/34926216/37789148-8efc-45be-b9d6-6b3ab11e858a

![The 2015 one](https://github.com/lightbeam24/CustomTube/assets/34926216/675e0a57-b37f-4da0-a57a-820b939f1fb2)

The above are with chapters. Here it is without.

https://github.com/lightbeam24/CustomTube/assets/34926216/9eac7a0c-ebba-487e-8f32-a388787f62cb

![The 2015 one without chapters](https://github.com/lightbeam24/CustomTube/assets/34926216/7d015c9c-276d-4151-8619-6cd954d5e972)

The extending issue for no-chapter videos happens up until 2014, when the player size got increased. There is still a bit on the right, but its usually good.
For chapter videos, it always happens, even up to current day layout.
This is one infuriating bug that i think needs to be fixed.
Thank you!

**Comment by lightbeam24** [comment]
I was gonna mark this as a duplicate of issue 11, but in short, I think one of YouTube's experiments is messing with the video resizer. I found a solution, and it will be present in the next update. But for now, zoom in and zoom out again to fix it, or enter fullscreen and exit it again.

**Comment by lightbeam24** [comment]
How's the situation looking in 1.2.3? It should be significantly better now.

**Comment by lovebug0706** [comment]
I can’t look right now because we’re in the process of moving and my PC has
already been moved, but I will check once we’re done.

**Comment by lovebug0706** [comment]
Works way better, Thanks!
