### ISSUE TITLE
On channels that doesn't have a banner image uploaded, the layout is not showen correctly.

### ISSUE THREAD

**Issue by GemplelyTivadar** [lightbeam24/CustomTube#114]
Since the latest layout update by YouTube, on channels that doesn't have a custom banner image uploaded, CustomTube no longer shows their profile picture. Also CustomTube used to restore the old default banner, that also doesn't show up. 
![Screenshot from 2023-10-29 20-40-56](https://github.com/lightbeam24/CustomTube/assets/95102462/da10a3c7-3cdd-4a17-8323-5714dbec9ed0)

**Comment by lightbeam24** [comment]
Yep, I gotta get to this soon. It's especially problematic on older layouts like 2008.

**Comment by GemplelyTivadar** [comment]
Closing because the new update fixed it.
