### ISSUE TITLE
possible port of 2005 and 2006 players?

### ISSUE THREAD

**Issue by JennyBean333** [lightbeam24/CustomTube#115]
https://github.com/purpletheblaze/viewfinder-2005
https://github.com/purpletheblaze/viewfinder-2006
would you be able to port these over into customtube at some point? theyre html5 remakes of the original flash players, and im guessing youd like to be able to make these themes later on?

**Comment by lightbeam24** [comment]
No. CustomTube does not use the actual old players. The player styles are just the current player styled to look like the old players, much like the layouts themselves. I don't know how to do it any other way. I also have little interest in recreating the players from that era as of now.
