### ISSUE TITLE
Hovering wont complete video's title.

### ISSUE THREAD

**Issue by nknm** [lightbeam24/CustomTube#116]
If im looking at videos in the main page it will complete the title if hover the partial title (if its too long partial is the part you can read and if you hover it should display the entire title below it) but when Im viewing on people's channels or the side bar (the one when you are viewing a video and shows recommended videos on the right) it just simply does nothing, and sadly the URL display at the bottom is just the normal URL like normal youtube, idk if that's a bug or a feature (the hover thing, the URL is how it is intended to be). Im not very good at explaining things i can provide screenshots or try to word it better if its confusing. Have a good day!

**Comment by lightbeam24** [comment]
You mean the tooltip that shows the video's full title? Tooltips are shown at the browser level (at least the ones we're talking about here), so I don't think it's even possible for this to happen. **You need to be hovering over the video title itself** for the tooltip to display.

Example:
![Screenshot_2023-10-31_18-52-59](https://github.com/lightbeam24/CustomTube/assets/105595945/65fb33d9-88ad-4f19-b93c-cbb825e9232c)

**Comment by nknm** [comment]
yeah exactly that, oh well not the end of the world, thanks for the reply <3
