### ISSUE TITLE
[issue] 2012 - 2015 player bar doesnt stretch all the way in full screen

### ISSUE THREAD

**Issue by lovebug0706** [lightbeam24/CustomTube#119]
The red bar at the top of the player doesn't stretch all the way in full screen. I have a 1920x1080 monitor.
2012: ![2012 red bar not stretching all the way, but the bottom bar does](https://github.com/lightbeam24/CustomTube/assets/34926216/087df635-2629-4d21-8529-7e4551fc25e6)
2013-15: ![Same thing as above, but 2013-2015 red bar](https://github.com/lightbeam24/CustomTube/assets/34926216/5ada9e82-02c8-4158-b493-870c3c5c4432)
And heres how its supposed to look (ignore the captions and the annotations covering some of it, i took it from a video from 2014.) 
![A bit of a caption and a bit of an annotation blocking a perfectly widescreen 2013-2015 red bar](https://github.com/lightbeam24/CustomTube/assets/34926216/d35c757e-d3b5-4969-acd8-b89f5091c8ff)
This is a _very minor_ inconvenience for me, but if you can fix it that would be great.
Thank you!

**Comment by lightbeam24** [comment]
I tried for literal hours to get this to work in fullscreen when I was developing the player styles, unfortunately I could not figure it out.

**Comment by cyfung1031** [comment]
FYI. Install https://greasyfork.org/en/scripts/457319-youtube-video-resize-fix should fix
