### ISSUE TITLE
[Feature Suggestion] Option to choose between multiple video player sizes.

### ISSUE THREAD

**Issue by GemplelyTivadar** [lightbeam24/CustomTube#12]
I like the extension so far, but there are some features I miss. One of them being the option to choose a preferred video player size. The current video player in my opinion is too small. I know if I turn off the "Force consistent video size" option, then the video player is reverted to the default YouTube size, but that's too big for my taste lol. Also the video player won't keep the 16:9 aspect ratio that way.

**Comment by lightbeam24** [comment]
@UnderscoreAngel 

> i already presented this idea to lightbeam, the problem is that we don't know how the javascript for the player works that well yet, i've took a look at it myself, yet i still haven't found a way to do it

Actually, changing the player size is unrelated to the resizing issue.

@GemplelyTivadar 

Good idea, I'll look into it! Just know that it will most likely be exclusive to layouts from 2014 and later. The smaller video size is pretty much integral to layouts from 2013 and earlier, and allowing larger video sizes would mess with the formatting of the page altogether (especially on the 2012 layout).

**Comment by UnderscoreAngel** [comment]
> @UnderscoreAngel
> 
> > i already presented this idea to lightbeam, the problem is that we don't know how the javascript for the player works that well yet, i've took a look at it myself, yet i still haven't found a way to do it
> 
> Actually, changing the player size is unrelated to the resizing issue.
> 
> @GemplelyTivadar
> 
> Good idea, I'll look into it! Just know that it will most likely be exclusive to layouts from 2014 and later. The smaller video size is pretty much integral to layouts from 2013 and earlier, and allowing larger video sizes would mess with the formatting of the page altogether (especially on the 2012 layout).

oh ok, you might aswell look forward to it

**Comment by lightbeam24** [comment]
Added in 1.1.0.

**Comment by GemplelyTivadar** [comment]
> Added in 1.1.0.

Thanks!
