### ISSUE TITLE
2012 layout Theater Mode doesn't increase the video size

### ISSUE THREAD

**Issue by anaseig** [lightbeam24/CustomTube#125]
![Screenshot 2023-11-09 113233](https://github.com/lightbeam24/CustomTube/assets/70536934/26d26c49-e5fb-4161-9b3f-99c51aeadcca)

When I press Theater Mode:
-- It leaves a lot of black space and the resolution of the video does not increase.
-- the Theater Mode icon dissapears.

**Comment by lightbeam24** [comment]
Theater mode is unsupported on all layouts older than 2014. It says this in the config window. Those layouts force the entire site to be a specific width, which would make supporting theater mode pretty complicated. There are currently no plans to make theater mode work with those older layouts.

![Screenshot_2023-11-08_23-41-33](https://github.com/lightbeam24/CustomTube/assets/105595945/cd6d102e-6282-4b41-b9bd-a2839ae29957)
