### ISSUE TITLE
2017 and 2016 layouts dont automatically change profile pictures to be unrounded

### ISSUE THREAD

**Issue by zaxel-github** [lightbeam24/CustomTube#128]
title says it all, small issue.

![Screenshot 2023-11-13 120334](https://github.com/lightbeam24/CustomTube/assets/79190563/2870a6fc-94d0-49ba-ae19-d83c045650f3)
2017

![Screenshot 2023-11-13 120348](https://github.com/lightbeam24/CustomTube/assets/79190563/d2fca0eb-fe99-40cf-bb45-185a1db6ff5d)
2016

**Comment by lightbeam24** [comment]
Its just the topbar profile picture. It was already rounded in 2016 and 2017. You can unround it by enabling "unround profile pictures" in tweaks.
