### ISSUE TITLE
White box in background when loading

### ISSUE THREAD

**Issue by Zhrak81** [lightbeam24/CustomTube#132]
Whenever youtube loads, front page, subs, watch page, there is for a short time a white box in the background, which disappears after a few seconds. As far as I can tell this only occurs in the polymer layouts.
Have tried in Firefox and Edge, with multiple extensions and only customtube.
Not certain when it started, but at least a week or two ago.

![YTbox](https://github.com/lightbeam24/CustomTube/assets/151552749/0310056e-f84d-40f2-bd7f-2f9e8cc03bef)

**Comment by lightbeam24** [comment]
I had this happen once when I temporarily switched to dark mode a couple days ago, however I am unable to reproduce it now. If I ever see it again, I'll try looking into it.

**Comment by Zhrak81** [comment]
For whatever reason is is not happening anymore since this morning, and I don't remember changing anything, but not gonna complain.
