### ISSUE TITLE
Support for compatibility with DeArrow extension?

### ISSUE THREAD

**Issue by yukudbzn** [lightbeam24/CustomTube#136]
The title glitches when I use the DeArrow extension with CustomTube enabled.

**Comment by yukudbzn** [comment]
![image](https://github.com/lightbeam24/CustomTube/assets/95426023/d182189f-5892-4654-b191-8a7e6d3cf51e)

**Comment by lightbeam24** [comment]
I've never heard of that extension before. The developer of that extension will have to make it compatible with CustomTube instead.
