### ISSUE TITLE
Fix this!

### ISSUE THREAD

**Issue by uy813** [lightbeam24/CustomTube#139]
Remember This Bug? 
![Screenshot_63](https://github.com/lightbeam24/CustomTube/assets/129725038/08b953da-50b2-4110-a0e5-d292daa7b708)
this is getting annoying.
but then, when i switch to my alt account. it looks like it's fixed. but if i switch back to my main account, it's not fixed! what is going on? can you tell me?

**Comment by lightbeam24** [comment]
It's an experiment that one of your accounts has. Lots of people have been getting this experiment, but I haven't, therefore I couldn't fix this even if I wanted to right now. Closing as a duplicate.
