### ISSUE TITLE
Different video player styles for each layout

### ISSUE THREAD

**Issue by Techfromthepast123** [lightbeam24/CustomTube#14]
![YouTube_video_player_history](https://github.com/lightbeam24/customtube/assets/112059671/274f6b1e-b481-4ebf-9642-b39a38ead910)
Will it be possible to add the original style players that came with the original layout ?
It would be cool if it did

**Comment by lightbeam24** [comment]
Yeah I plan to do that in the future, it's just not the highest priority right now.

**Comment by TorutheRedFox** [comment]
for doing the player chrome i suggest implementing the progressbar manually as the width is hardcoded in the player's javascript and breaks if you force it to span the full width

**Comment by lovebug0706** [comment]
Heres a full image of what was sent with all the different players, in case if it eventually does go back that far.
![Image at top, but this time going back to 2005](https://github.com/lightbeam24/CustomTube/assets/34926216/337a33fc-d19a-4319-a7b8-6ef2561d4a57)
