### ISSUE TITLE
Header bug, unstyled searchbars in Firefox

### ISSUE THREAD

**Issue by okamitime** [lightbeam24/CustomTube#142]
![msnmsgr_OwSYB6XG2C](https://github.com/lightbeam24/CustomTube/assets/77937632/4c38be20-5118-4d97-a92b-7779d04571e0)
![msnmsgr_kP2BwvUsYY](https://github.com/lightbeam24/CustomTube/assets/77937632/3f1a16ff-fd22-4076-abca-cb7c3647da9f)
![msnmsgr_6ZBW1FXmmy](https://github.com/lightbeam24/CustomTube/assets/77937632/24a16f46-e6b7-4684-97bb-ae8adc3260c9)
![msnmsgr_9rsIRh0d4o](https://github.com/lightbeam24/CustomTube/assets/77937632/f6ca38b3-593c-419c-8c5e-82cb922a1c07)
Layouts from 2013 onwards have the searchbar in the correct place but they are also not styled properly.
![msnmsgr_hIUxc6DZWP](https://github.com/lightbeam24/CustomTube/assets/77937632/f205c207-447c-4ea3-af3d-0544fbc834d9)
![msnmsgr_jnYK3r6mCE](https://github.com/lightbeam24/CustomTube/assets/77937632/02c70c40-7e25-4e86-809a-8ac8e19a001d)

**Comment by lightbeam24** [comment]
You're trying to use the Material Search Bar style with the older layouts, which doesn't work. In the config window, go to Topbar, and change Search Bar Style back to Auto.
