### ISSUE TITLE
Incorrect font for video title on watch page (affects all layouts)

### ISSUE THREAD

**Issue by elaymm4** [lightbeam24/CustomTube#145]
So it seems like some kind of experimental YT update, because I don't have that in incognito mode, but it does appear on my account. The font for video title on watch page is overriden now with this bold one. Screenshots provided. Tested without any extra plugins or scripts - only CustomTube is used.
![normal yt](https://github.com/lightbeam24/CustomTube/assets/32716814/7fc8979c-354f-475e-9f91-2595b4ecc18e)
![2014](https://github.com/lightbeam24/CustomTube/assets/32716814/57f54cc1-752a-42a7-8d59-f1b0924b7abc)
![2008](https://github.com/lightbeam24/CustomTube/assets/32716814/a31468b1-9117-42ad-b139-aaeea2d5a9fb)

**Comment by lightbeam24** [comment]
Should be fixed as of 1.2.5.2.
