### ISSUE TITLE
Like and dislike buttons formatted weird on 2015-2017 Layouts

### ISSUE THREAD

**Issue by monkpipos** [lightbeam24/CustomTube#147]
might be due to the enhancer for youtube extension I have but still weird 
![image](https://github.com/lightbeam24/CustomTube/assets/77772118/bada40ac-3aae-4e25-8710-a2e68faaff1a)

**Comment by lightbeam24** [comment]
Does it still happen? Sorry for not getting to this earlier.

**Comment by monkpipos** [comment]
Oh apologies for not responding but it's been fixed since sometime last week

**Comment by lightbeam24** [comment]
Yeah, this should've been fixed in 1.2.6.
