### ISSUE TITLE
Progress bar not extending to borders of screen

### ISSUE THREAD

**Issue by Nlk29** [lightbeam24/CustomTube#153]
Hi,

As you can see, the progress bar is not extending to the border of the screen. This only happens in fullscreen and is independent of the theme.

Is there a setting that i need to change or is this a bug?

I am using a 16:10 display btw.

![image](https://github.com/lightbeam24/CustomTube/assets/78368286/f020d64c-e529-4b44-848a-1b1f0e671547)

**Comment by lightbeam24** [comment]
Not a bug, it's just impossible to get it full width in fullscreen (to my knowledge).
