### ISSUE TITLE
The sidebar sometimes won't instantly disappear if switching from YouTube home page to channel

### ISSUE THREAD

**Issue by Patricek0056** [lightbeam24/customtube#16]
### Problem description:
The sidebar sometimes won't instantly disappear if I switch from YouTube home page to any channel (In this case the “Andrej Danko” channel).

### Other details:

- Browser version: Firefox v113.0.2
- YouTube site zoom percentage: 100%
- YouTube layout: 2012 layout.
- OS version: Windows 11 22621.1778
- OS architecture: 64-bit
- Browser architecture: 64-bit
- CPU: AMD A10-7860K
- RAM: 16,0GB DDR3
- Motherboard: MSI A88XM-E35 V2
- Graphics: 1024MB ATI AMD Radeon R7

### Screenshots & Videos:
See it yourself from this short video:
https://www.mediafire.com/file/sa9vc089hzjxjdj/The_sidebar_sometimes_won%2527t_disappear_if_switching_from_YouTube_home_page_to_channel.mp4/file

**Comment by Patricek0056** [comment]
I think the 2012 layout.

**Comment by lightbeam24** [comment]
That's simply a quirk of how CustomTube works. It only checks for a new URL every half second or so to avoid potential performance issues. In the 2012 layout, it decides whether to show or hide the sidebar based on the current URL, so yes, this would be a 2012 exclusive issue.

I would close this as not planned, but I'm actually thinking of experimenting with another possible way to detect what page the user is on. It might fix this, it might not. We'll just have to see.

**Comment by lightbeam24** [comment]
> Sorry for advocacy, but this issue is so annoying, not only to me, but also for other people.

Oh, who are these "other people"? If there's enough demand for something, I push it up my priority list a bit. I haven't had anyone else mention this though.

> My opinion is, that it would be possible even without performance issues.

With the current way the extension is built, the only possible way to fix this would be to check for a new URL every 10 milliseconds (which means it would check for a new URL 100 times per second) or something crazy like that. That could very well cause performance issues, and is overall a horrible way to do things. Right now it checks for a new URL once or twice per second.

**Comment by lightbeam24** [comment]
I actually think update 1.0.4 might've accidentally fixed this because of unrelated code improvements. It doesn't happen to me anymore. Is it also fixed for you?

**Comment by Patricek0056** [comment]
Partially fixed, but better than before, so you can close this.

**Comment by lightbeam24** [comment]
Alright, thanks
