### ISSUE TITLE
Broken like/dislike

### ISSUE THREAD

**Issue by portex7000** [lightbeam24/CustomTube#168]
Like/dislike button broken (second time for me)
![image](https://github.com/lightbeam24/CustomTube/assets/150171265/5bc98281-ca29-4292-a35b-4eef1eb83471)

**Comment by lightbeam24** [comment]
I'll look into this when I get the chance.

**Comment by ParkerGit2328** [comment]
And even the icons disappeared

**Comment by lightbeam24** [comment]
Fixed in 1.2.7.2.
