### ISSUE TITLE
Use the old favicons for every YouTube layout

### ISSUE THREAD

**Issue by Aleksandra0056** [lightbeam24/CustomTube#17]
### Problem description:
- The YouTube has old favicons in 2012, 2013, and other layouts, but this extension is not changing the favicons for the YouTube.
- **NOTE:** Favicon is icon in head of website (also in Firefox tabs are favicons).

### Expected results:
- The YouTube should use the old favicons in 2012, 2013, and other layouts.

### Other details:
- Browser version: Firefox v113.0.2
- YouTube site zoom percentage: 100%
- YouTube layout: Almost all layouts.
- OS version: Windows 11 22621.1778
- OS architecture: 64-bit
- Browser architecture: 64-bit
- CPU: AMD A10-7860K
- RAM: 16,0GB DDR3
- Motherboard: MSI A88XM-E35 V2
- Graphics: 1024MB ATI AMD Radeon R7

### Where to find the old favicons?
- See the https://youtube.com in [Wayback Machine](https://web.archive.org/).

**Comment by Patricek0056** [comment]
And what issues have this extension?

**Comment by lightbeam24** [comment]
1. The extension doesn't even attempt to restore the old Playlist page for any of the old layouts.
2. The extension doesn't even attempt to restore the old History page. What's worse is that the History page is broken on the 2012 layout.
3. The extension doesn't restore the old channel page on the 2019 layout.
4. The extension only restores *some* of the old icons.

**Comment by Patricek0056** [comment]
Thank you for quick response, I hope, that you will fix these major issues soonest as possible.

**Comment by elaymm4** [comment]
So, what about now?

**Comment by lightbeam24** [comment]
Implemented in 1.2.7/1.2.7.1.
