### ISSUE TITLE
Video Player Bug

### ISSUE THREAD

**Issue by frostylll** [lightbeam24/CustomTube#171]
Whenever I go to watch a video, the autoplay button still appears which makes it look out of place.

![image](https://github.com/lightbeam24/CustomTube/assets/120616941/d1c17e21-4a51-4ca3-b12b-f73c55c6b0a8)

**Comment by lightbeam24** [comment]
Duplicate. Right now replacing the watch metadata HTML is top priority, but this should either come soon after that.
