### ISSUE TITLE
More things about the "current" layout

### ISSUE THREAD

**Issue by MesaBlack** [lightbeam24/CustomTube#172]
![image](https://github.com/lightbeam24/CustomTube/assets/132141735/6e4debfc-9c9a-41a1-80ab-7f95e56c5938)
layout was set is current (disabled)

**Comment by lightbeam24** [comment]
I really can't worry about this right now. I'm working on a complete rework of the watch page that will affect all layouts (except disabled). Besides, this is basically the same problem as was reported in #162. Closing as a duplicate.
