### ISSUE TITLE
Option for Unused 2016 (2017) YouTube Logo

### ISSUE THREAD

**Issue by HAYDENCRAFT2008** [lightbeam24/CustomTube#174]
![IMG_1965](https://github.com/lightbeam24/CustomTube/assets/141458603/1c03779a-8b60-4c10-8c73-5176cd498ef1)

I know you don’t like suggestions but I was wondering if you would add this unused logo as an alternate option since you added the alternate unused search bar (I think this would’ve accompanied the logo too)

**Comment by lightbeam24** [comment]
Adding an option to choose your logo is already going to be a little complicated, and this logo is (let's not sugarcoat it) really ugly. *Mayyybbeee* it could be an option in the far future, but for the sake of not having a million different issues open at once, I'm closing this as not planned.

**Comment by HAYDENCRAFT2008** [comment]
oh yeah I know it's ugly.

**Comment by lightbeam24** [comment]
I haven't seen any archive or even screenshot of YouTube using that logo anyway.

**Comment by HAYDENCRAFT2008** [comment]
It went unused.

**Comment by lightbeam24** [comment]
I've seen the logo before, I just haven't seen it used in the YouTube website in any form.

**Comment by HAYDENCRAFT2008** [comment]
Ohhh, yeah I don’t think it was used directly on the website itself ever
