### ISSUE TITLE
Youtube Video Glitch

### ISSUE THREAD

**Issue by burnsboyamazing** [lightbeam24/CustomTube#176]
At https://www.youtube.com/watch?v=nAivZ8nLU1o, a few frames starts dropping the digits on the connection in docs.google.com for debug info.
[Video Glitch in docs.google.com Screen recording 2024-02-04 1.27.34 PM.webm](https://github.com/lightbeam24/CustomTube/assets/154830140/4b447b0a-1f88-4dbf-a1ce-fed455f3303e)
![Screenshot 2024-02-04 1 31 11 PM](https://github.com/lightbeam24/CustomTube/assets/154830140/8ba8fd81-6efd-4274-951a-72cc0658cc3d)
At the nimbus capture.

**Comment by burnsboyamazing** [comment]
At https://github.com/burnsboyamazing/bugs/issues/68.

**Comment by lightbeam24** [comment]
### ?????????????

What are you even trying to say here? Does this even have anything to CustomTube? Are you saying that CustomTube slows down the connection or something? Are you even *using* CustomTube? You're using the modern player style, and the rest of the page is cropped out, so I genuinely can't tell!

I don't see how this would happen, as CustomTube makes very little modifications to the player, and doesn't mess with the way it connects at all.

**Comment by burnsboyamazing** [comment]
Exactly!

**Comment by lightbeam24** [comment]
Exactly what?

In case you're not aware, CustomTube is a browser extension that lets you use the old (superior) YouTube layouts. If you think this is an official YouTube GitHub repository or something, you are gravely mistaken.

Here is a screenshot from the in development version of CustomTube 1.3.0:

![Screenshot 2024-02-04 134236](https://github.com/lightbeam24/CustomTube/assets/105595945/27ce38d2-402e-4f3a-9e8e-fe79c00535c5)

CustomTube should have no effect on the YouTube player's ability to stream videos, as it's basically just the regular YouTube website but with better CSS.

**Comment by burnsboyamazing** [comment]
Ok, thanks for the clarification.

**Comment by burnsboyamazing** [comment]
Ok, thanks.
