### ISSUE TITLE
Youtube Video Glitch at https://github.com/lightbeam24/CustomTube/issues/176

### ISSUE THREAD

**Issue by burnsboyamazing** [lightbeam24/CustomTube#177]
Youtube debug videos at https://github.com/lightbeam24/CustomTube/issues/176.
[Video Glitch in docs.google.com Screen recording 2024-02-04 1.27.34 PM.webm](https://github.com/lightbeam24/CustomTube/assets/154830140/d09f2346-a897-4914-8df5-154ecefe0f21)
![Screenshot 2024-02-04 1 31 11 PM](https://github.com/lightbeam24/CustomTube/assets/154830140/e3660e8a-050e-410d-8f67-8ad023af2205)
[Debug video of Video Glitch in docs.google.com Screen recording 2024-02-04 1.31.46 PM.webm](https://github.com/lightbeam24/CustomTube/assets/154830140/51faecef-ce58-4ff2-9414-9cefed7d8647)
[Long Debug video of Video Glitch in docs.google.com Screen recording 2024-02-04 1.33.02 PM.webm](https://github.com/lightbeam24/CustomTube/assets/154830140/9103b70c-84d3-4dc4-af6a-fd9d81605f6e)
At https://www.youtube.com/watch?v=nAivZ8nLU1o, between 3:00 and 5:30 mark, there is also a video glitch at docs.google.com.
At the nimbus capture, but do not delete videos or channels or strike videos with copyright claim.

**Comment by lightbeam24** [comment]
You created a duplicate issue of your own issue.
