### ISSUE TITLE
Youtube Did it Again!

### ISSUE THREAD

**Issue by uy813** [lightbeam24/CustomTube#209]
They Fixed The Channel UI Page and now it looked worse.
![image](https://github.com/lightbeam24/CustomTube/assets/129725038/62fc25dd-0a0e-4fcd-bd0d-9ef44e0ec6c3)

**Comment by Gravarty** [comment]
I recently read on Reddit that lightbeam is taking a break on fixing CustomTube.
(which i can understand, Google keeps messing with the YouTube page everyday).

The last update was in februrary. So expect much more things to break in the coming days.

**Comment by uy813** [comment]
Mine Was Fixed. The Channel Ui Was Fixed. so maybe you're right. man what am i doin here? i'm closing the issue
