### ISSUE TITLE
you guys can stop creating new issues

### ISSUE THREAD

**Issue by uy813** [lightbeam24/CustomTube#232]
lightbeam24 have never been awnsered for 3 months. he took a break. if hes still 
on the break, not awnsering for 8 months or year, CustomTube will be Dead. No Awnsers, No Updates. No Updates, No Popularity. No Popularity, No CustomTube. No CustomTube, No lightbeam24. i remember his youtube 2012 css style. i installed it on stylus. it looked bit good. but cosmic cat looks too good but lots of bugs. i'm sure he will be here somewhere and come back with us. hes still alive. we will patiently wait. Time will Tell. _(and yes i've heard your messages.)_

**Comment by NewSummo** [comment]
stop whining

**Comment by MesaBlack** [comment]
please shut up. they're cooking something else

**Comment by uy813** [comment]
both of you pissed me off. i tried to do my best to tell. but you bitches stopped me

**Comment by uy813** [comment]
> stop whining

what do you mean whining?

**Comment by MesaBlack** [comment]
> both of you pissed me off. i tried to do my best to tell. but you bitches stopped me

Hey, chill the fuck.

**Comment by uy813** [comment]
> > both of you pissed me off. i tried to do my best to tell. but you bitches stopped me
> 
> Hey, chill the fuck.

then stop giving me dislike and i will be calm

**Comment by MesaBlack** [comment]
You've barely done anything on the github looking at your history

**Comment by MesaBlack** [comment]
What I've learned from another repo is when the creator sees this, they'll realize that when the comments are on, sometimes there are people who are prone to go... insult each other. This is why I don't call fanbases communities. People are bound to go uncivil.

**Comment by uy813** [comment]
> What I've learned from another repo is when the creator sees this, they'll realize that when the comments are on, sometimes there are people who are prone to go... insult each other. This is why I don't call fanbases communities. People are bound to go uncivil.

i told you to stop giving me a dislike

**Comment by MesaBlack** [comment]
Then, STOP BITCHING.

**Comment by krystian3w** [comment]
Only with admin/high premission in repo/organization can be removed:

![obraz](https://github.com/lightbeam24/CustomTube/assets/35370833/d391aa32-15a6-4ff2-9af3-2d95f37387cc)


Then link should opens 404 error for community and admin of repo should see who deleted.

**Comment by MesaBlack** [comment]
why did you thumb mine down? They were kinda whining
