### ISSUE TITLE
Wrong text appearing on the view counter's place

### ISSUE THREAD

**Issue by GemplelyTivadar** [lightbeam24/customtube#24]
For some reason on the view counter's place this text appearing: Song 1 of 2.
This is the second time I encountered this bug. After refreshing the page, or switching to another video, it goes back to normal.
![Screenshot from 2023-06-02 13-24-19](https://github.com/lightbeam24/customtube/assets/95102462/7cc3c250-0556-4d04-8989-88723194c7d2)

**Comment by lightbeam24** [comment]
What video is this? This looks like something that would only happen on specific videos. I had it happen once, but wasn't sure why it happened.

**Comment by GemplelyTivadar** [comment]
I don't remember the exact video I took this screenshot from, but I think I found the source of that text.
After submitting this issue I thought that it might be related to copyright claims in the video description.
So I started randomly clicking on videos that has multiple music in it and it looks like that's gonna be it.
I recorded a video showcasing it. It took me a while to get this bug, since it not always appears.
Anyways, here's the video I recorded: https://www.youtube.com/watch?v=ZZTLGxXGWis

**Comment by lightbeam24** [comment]
Thanks. I think a have a couple ideas for things that might fix it. For now, just refresh the page when it happens.

**Comment by Patricek0056** [comment]
And which layout is that? Can you edit the issue description and write the layout year? E.g. 2012, 2013, or 2017

**Comment by UnderscoreAngel** [comment]
> And which layout is that? Can you edit the issue description and write the layout year? E.g. 2012, 2013, or 2017

it has happened to me aswell, it's from the layouts from 2017 - 2016

**Comment by lightbeam24** [comment]
> > And which layout is that? Can you edit the issue description and write the layout year? E.g. 2012, 2013, or 2017
> 
> it has happened to me aswell, it's from the layouts from 2017 - 2016

CustomTube creates it's own view count element and uses it for all layouts, so I don't even need to test other layouts to know they are all affected.

I'm currently testing out a better (in theory) way to apply the view count to the custom view count element, which should fix this issue.

**Comment by lightbeam24** [comment]
I just released version 1.0.4 which uses a new method to get the view count. With this new method, it would be impossible for this to happen. Closing as completed unless proven otherwise.
