### ISSUE TITLE
Notif popup flikers when opened

### ISSUE THREAD

**Issue by Caddy8970** [lightbeam24/CustomTube#26]
https://github.com/lightbeam24/customtube/assets/113631055/6f677543-982f-438e-89bd-fbaa1918c97f

OS: Windows 11 22631.1835 (Insider beta)
Browser: Firefox Nightly 116.0a1

**Comment by lightbeam24** [comment]
Are you sure CustomTube causes this? As of now, the notifications panel is almost completely unmodified by the extension. Try disabling CustomTube and see if it still happens.

If it does still happen, could you try it on the 2012, 2013, and 2019 layouts, to see if it's a layout-specific bug?

**Comment by Caddy8970** [comment]
it seems to happen randomly, some times it does, some times it doesn't. It mostly happens when whatching videos from playlists. disabling the addon fixes the issue completely. layout-specific? not sure since it's an hard bug to replicate on pourpuse. 
(anyways sorry for any typo i made)

**Comment by Caddy8970** [comment]
im currenly using layout 2014 on the latest version (1.0.4)

**Comment by lightbeam24** [comment]
Okay. I have to admit that I don't know how to fix this as of now since I can't reproduce it myself, but I'll keep it in mind anyway. I'll let you know if I figure anything out.

**Comment by Caddy8970** [comment]
It seems that it doesn't happen anymore. Still not sure what caused it

**Comment by Caddy8970** [comment]
Nope, it's happening again

https://github.com/lightbeam24/CustomTube/assets/113631055/c3e4bb8e-5934-42ee-80c4-ffafa6eaf04e

layout: early 2013

**Comment by lightbeam24** [comment]
Is it fixed now? I have a feeling this is related to issue #34 which is fixed.

**Comment by Caddy8970** [comment]
Yup, i'ts fixed
