### ISSUE TITLE
The share button doesn't work properly

### ISSUE THREAD

**Issue by GemplelyTivadar** [lightbeam24/CustomTube#27]
The share button on watch pages only works on the first video I watch, if I switch to another video, the share button still acts like if I was still watching the first video. No matter how many videos I open, it always showing the first video's url.

This is the first video i opened. The share button shows the correct url.
![share button 1](https://github.com/lightbeam24/customtube/assets/95102462/526b47a8-53a4-49d7-a100-96d605ab8d38)

This is the second video I opened. The share button shows the previous video's url.
![share button 2](https://github.com/lightbeam24/customtube/assets/95102462/79ee8162-9ece-4002-97f1-ae967b21508e)

And this is the third video I opened. Still showing the first video's url.
![share button 3](https://github.com/lightbeam24/customtube/assets/95102462/ee5c36a2-b745-4623-a9ce-0fae379aa5f6)

**Comment by GemplelyTivadar** [comment]
I forgot to mention that this bug is present in 2012 - 2017 layouts, 2019 and the disabled option are unaffected.

**Comment by lightbeam24** [comment]
Ah, I think I know why this happens, however some things would theoretically need to be significantly reworked in order to fix this. I imagine that trying to fix this right now could introduce other, much more serious bugs. I might look into it sometime down the line, but I can't say when.

**Comment by lightbeam24** [comment]
The aforementioned watch button rework as occurred as of 1.2.5, so this is fixed now.
