### ISSUE TITLE
Channel page doesn't look right

### ISSUE THREAD

**Issue by gameshowrecaps** [lightbeam24/customtube#28]
![offcenter](https://github.com/lightbeam24/customtube/assets/57842610/395a4837-26f9-48ce-b7a5-f88c8d5bd581)

**Comment by lightbeam24** [comment]
Does this happen consistently, or only sometimes?

What is your screen resolution and zoom level?

**Comment by gameshowrecaps** [comment]
1920x1080, normal zoom and on the 2017 default layout.

**Comment by lightbeam24** [comment]
Just to be certain, could you go to this site (https://www.rapidtables.com/web/tools/window-size.html) and tell me what it gives you for *inner window size*? I was only able to reproduce this issue with an inner window width of around 1266 pixels or lower. I know Windows likes to scale the UI up by default, resulting in a smaller browser window.

If your inner window width is indeed 1920 pixels or somewhere close, are you using any other extensions, userscripts, or userstyles that affect YouTube? If so, check to see if one of them is causing this (CustomTube wasn't tested with any other scripts).

It's supposed to look like this (I'm also using a 1080p monitor at 100% zoom):

![Screenshot_2023-06-22_14-39-29](https://github.com/lightbeam24/customtube/assets/105595945/85452d6d-0edc-4221-b213-7a72606a4999)

Either way, while not ideal, setting "Channel videos Sort by dropdown" to "off" in CustomTube settings should get rid of this issue.

**Comment by gameshowrecaps** [comment]
Inner size: 1536x731

I turned Channel videos Sort by dropdown to on and that seemed to fix my issue.

**Comment by lightbeam24** [comment]
The issue shouldn't have been closed, because the fact that the dropdown didn't work with your zoom level was still a bug. But I'm about to release an update that completely fixes it, so the issue can remain closed.
