### ISSUE TITLE
Topbar stays white in Cinema mode

### ISSUE THREAD

**Issue by WerDei** [lightbeam24/customtube#3]
When using anything other than "Use current YouTube layout", the topbar does not become black in Cinema mode. The icons on the topbar still change color to white though, which makes them invisible.

Screenshot of how it looks:
![image](https://github.com/lightbeam24/customtube/assets/48105614/a6b2ad1b-031f-46e8-8615-e69b83756d36)
And how it *should* look loke:
![image](https://github.com/lightbeam24/customtube/assets/48105614/90beba06-23c0-47ce-846f-42890549062d)

(Very nice addon btw, I'll likely keep using it until Google inevitably breaks it)

**Comment by lightbeam24** [comment]
Ah, yes this is a problem. While you are correct about the topbar turning black for the 2019 layout, this isn't the case for layouts from 2017 and earlier, so just the icon colors will be fixed for those layouts. Will fix in either the next update or the one after that.

**Comment by WerDei** [comment]
Just got the 1.0.3 update, and it appears to be fixed. In the future, I'd suggest to create an option to force the topbar to be black in other layouts as well ('cos it looks nice), but it's not a deal-breaker for me - I like the 2019 layout most anyway.
Thank you for your work, mate!

**Comment by lightbeam24** [comment]
Thanks! Yeah, If I get around to it I will.
