### ISSUE TITLE
BUG: Comments cannot be deleted

### ISSUE THREAD

**Issue by sedwinj** [lightbeam24/CustomTube#34]
Attempting to delete a comment creates a confirmation dialogue to confirm the deletion. This dialogue closes itself after a few hundred milliseconds before the user has an opportunity to make a selection. Refreshing the page shows that the comment has not been deleted.

Using latest version of Firefox on Windows 10. Confirmed on all layouts (while using a few other extensions). Confirmed on the 2019 layout in a clean instance of Firefox with all other extensions disabled.

**Comment by gameshowrecaps** [comment]
Can confirm. I was trying to pin a comment.

**Comment by lightbeam24** [comment]
I am aware of the issue. I think I might know what's causing it but I'm not entirely sure yet. I'll look into it when I get the chance

**Comment by lightbeam24** [comment]
Fixed in 1.0.4.4.
