### ISSUE TITLE
All layout descriptions treated as links.

### ISSUE THREAD

**Issue by dp-zini** [lightbeam24/CustomTube#35]
This was fixed on the June 30th update but broken by todays update. It affects all layouts and causes them to change text color when hovered over with the cursor. Minor issue,

**Comment by lightbeam24** [comment]
But that isn't possible? description.css was not touched at all in 1.0.4.4, there's no way it could've been caused by this update.  It doesn't happen to me.

Maybe YouTube gave you an experiment that messes it up?

**Comment by UnderscoreAngel** [comment]
> This was fixed on the June 30th update but broken by todays update. It affects all layouts and causes them to change text color when hovered over with the cursor. Minor issue,

this bug was fixed in 1.0.4.3 if i'm not mistaken, you might be running an older version, go to about:addons > CustomTube > Click on the gear icon and select "Check for updates" 

![imagen](https://github.com/lightbeam24/CustomTube/assets/105066360/2b705c69-031d-4fdc-a502-884dd0f90a2c)

**Comment by UnderscoreAngel** [comment]
> This was fixed on the June 30th update but broken by todays update. It affects all layouts and causes them to change text color when hovered over with the cursor. Minor issue,

ok im kinda stupid i didn't read it well enough, if you already updated it and the issue persists try uninstalling CustomTube and reinstalling it as it might be your setting or browser, this can also be caused by an experiment, you can try signing out of your account and see if the issue persist there, it would be cool if you could share an screenshot or have some kind of console output :P

**Comment by dp-zini** [comment]
This happens on the 2019 and 2017 layouts, and I am on the latest update. I've uninstalled and reinstalled and switched accounts and the issue seems to persist. 

![image](https://github.com/lightbeam24/CustomTube/assets/130931805/0c8da598-3057-46a9-9255-6b49107e6d15)
![image](https://github.com/lightbeam24/CustomTube/assets/130931805/143cfd19-eb78-4a41-8f9f-4326fcd9efc8)

**Comment by lightbeam24** [comment]
> This happens on the 2019 and 2017 layouts, and I am on the latest update. I've uninstalled and reinstalled and switched accounts and the issue seems to persist.
> 
> ![image](https://user-images.githubusercontent.com/130931805/251569156-0c8da598-3057-46a9-9255-6b49107e6d15.png) ![image](https://user-images.githubusercontent.com/130931805/251569385-143cfd19-eb78-4a41-8f9f-4326fcd9efc8.png)

Purple text?? That's not even the same issue that was fixed in 1.0.4.3. Try disabling other extensions until it works (CustomTube was only tested with Return YouTube Dislike and uBlock Origin).

**Comment by dp-zini** [comment]
Yes, it was enhancer for youtube causing the problem. I was using the purple dark theme and for some reason that caused the issue. It just happened recently but disabling the theme fixed it. Thank you.
