### ISSUE TITLE
misplaced button in Youtube 2014 version

### ISSUE THREAD

**Issue by AV-Gaming** [lightbeam24/customtube#4]
Hey,

I read the other "issues" and it helped learn more about the project. Big respect to you lightbeam24 for making this.

I noted something odd,
![Untitled](https://github.com/lightbeam24/customtube/assets/130517741/3dd72afe-5ad5-4439-bb6e-3853983eefab)

I don't think that button is supposed to be up there with the logo, is it?

Apart from that - great work dude. Is there any way to support the project monetarily? Anything that allows me to remember my childhood in the modern age is priceless to me! But this does seem like something that might need constant maintenance, so best of luck to you! If the project is still around in 3, 6, 12 months from now, and still being worked on, I would be amazed and thankful.

The surprising thing to me is the sheer number of options you've gone for - one year is not enough, huh? Hey what if you could take "return youtube dislike" data, combined with real like data use it to visually represent dislikes as 5 stars, like really old youtube - 50 likes 50 dislikes could be 2.5 stars, 100 likes 50 dislikes could be 3.3333 stars, etc. I am just messing with you lol but having written that just now I like the idea myself.

**Comment by lightbeam24** [comment]
Actually that button is supposed to be up there. Here is the Wayback Machine capture I used as a reference: https://web.archive.org/web/20140620001615/https://www.youtube.com/
I suppose I could add an option to remove it if you'd like though.

Right now I don't have a donation method set up, and I'll need to figure out how to do so first. I hope I can get one set up sometime soon, once I do, any donations would be greatly appreciated!

Yep! One year is not enough. The project was made with the goal of being able to choose your YouTube layout with a single click, like it should be. It's also good coding experience I think.

Adding star ratings is actually a very good idea! Funny thing is, not only would star ratings be possible, but I wouldn't even have to create new star icons for any of the layouts. For whatever reason, YouTube STILL makes new star rating icons whenever they change the layout! Of course, it would just be visual though, and I can't say when it'll be added. But yeah, thanks for the idea!

**Comment by AV-Gaming** [comment]
Oh Hi,

Yes it appears I was mistaken, oops. And man, really wasn't expecting the trip back to the past upon clicking that wayback machine link... pheeeew.

...That said, thanks for the reply, and i'll make sure that if I report anything in the future, it'll be a genuine thing hopefully, not a false alarm like this time, lol.

**Comment by AV-Gaming** [comment]
oh, gotta close the issue!
