### ISSUE TITLE
Suggestion: "True" fullscreen mode from Youtube Redux.

### ISSUE THREAD

**Issue by kwan-vini** [lightbeam24/CustomTube#42]
![image](https://github.com/lightbeam24/CustomTube/assets/118130060/a3139393-ec88-454c-93b8-f82a0cc1b3bc)
![image](https://github.com/lightbeam24/CustomTube/assets/118130060/59c432e5-678d-4ec9-b36f-0e415a92b226)

Would be really cool! :)

**Comment by lightbeam24** [comment]
Alright, it'll be in the next update! Figured it out really fast actually.

**Comment by kwan-vini** [comment]
> Alright, it'll be in the next update! Figured it out really fast actually.

Nice! Thanks lightbeam!

**Comment by lightbeam24** [comment]
1.1.0 is out now, and True Fullscreen Mode is enabled by default.
