### ISSUE TITLE
White text on white search box. (Beta)

### ISSUE THREAD

**Issue by kwan-vini** [lightbeam24/CustomTube#43]
![image](https://github.com/lightbeam24/CustomTube/assets/118130060/27cbc25b-118c-4988-b3ac-9a56e3dbd832)
Affects all the hitchhiker layouts while in theater mode.

**Comment by lightbeam24** [comment]
Alright, thanks. Will be fixed in the next beta.

**Comment by lightbeam24** [comment]
Was fixed in 1.1.0 Beta 3.
