### ISSUE TITLE
Shorts don't show up since July 12?

### ISSUE THREAD

**Issue by fredlwm** [lightbeam24/CustomTube#46]
I guess that in July 12, YouTube moved the Shorts from https://www.youtube.com/feed/subscriptions to a separate bar, which points to https://www.youtube.com/feed/subscriptions/shorts, but if you try to access that link directly, it's empty.

Enabling the extension, the new separate bar is gone and you don't have access to the Shorts anymore.

**Comment by lightbeam24** [comment]
I see, okay. Hiding the Shorts shelf on subscriptions will become optional in 1.1.0.

**Comment by lightbeam24** [comment]
1.1.0 is out now with the option.
