### ISSUE TITLE
On shorts, when the like/dislike button is pressed, the icon becomes barely visible.

### ISSUE THREAD

**Issue by GemplelyTivadar** [lightbeam24/CustomTube#50]
![shorts dislike icon](https://github.com/lightbeam24/CustomTube/assets/95102462/d3d64d47-e2f7-4228-9c96-0e7b0fa6b028)

**Comment by lightbeam24** [comment]
Okay, will be fixed in 1.1.0.

**Comment by lightbeam24** [comment]
1.1.0 is out now with the fix.
