### ISSUE TITLE
Like button too small 

### ISSUE THREAD

**Issue by LemonadeSnake** [lightbeam24/CustomTube#51]
![image](https://github.com/lightbeam24/CustomTube/assets/78671572/c512fed9-1929-4a42-adc5-8066c0109d1a)
the button can't seem to fit the text or icon in

**Comment by lightbeam24** [comment]
I think you might have YouTube's new "rolling like count" experiment (where the like count updates in real time). I just found out about it today, so I'll look into fixing it soon.

**Comment by GemplelyTivadar** [comment]
Sadly my account also got this a/b testing today. Now all layouts are broken before 2019.

2012 - 2014 is just showing "??" where the like/dislike numbers should be. Also the page doesn't load correctly as seen on the image below.
![2014](https://github.com/lightbeam24/CustomTube/assets/95102462/415b42ce-730b-43dc-a5b0-13f18a30e92a)

On 2015 - 2017 the like and dislike buttons are gone, and the page is not loaded correctly here either. 
![2016](https://github.com/lightbeam24/CustomTube/assets/95102462/c3979699-8d20-4d29-90dc-99dbba6240fc)

After disabling the RYD compatibility, it's somewhat okay, but the like number is using the default YouTube font size.
![2016_2](https://github.com/lightbeam24/CustomTube/assets/95102462/61c3f826-6d10-409d-be80-cb5eef59085b)

Also, the description now has a bigger padding at the top, but I'm not sure if that's related to the new rolling likes.

**Comment by lightbeam24** [comment]
I'll probably have to create a new element within the like button for the like count. I plan to look into that soon.

Yes the extra padding seems to be related to the experiment, as it seems the view count and upload dates are also rolling numbers.

**Comment by lightbeam24** [comment]
Think this was fixed a little while ago. As it stands, Return YouTube Dislike's "Re-format like numbers" option needs to be off for it to work though.
