### ISSUE TITLE
Add-on breaks the additional details box for a report

### ISSUE THREAD

**Issue by iansquenet** [lightbeam24/CustomTube#53]
When I get to providing additional details for a reported video, I'm unable to write anything in the provided text box.

![image](https://github.com/lightbeam24/CustomTube/assets/36297463/d4349ac6-3112-4539-86b3-923912f360de)

**Comment by lightbeam24** [comment]
I'll look into it.

**Comment by lightbeam24** [comment]
Should be fixed in 1.1.0.1.
