### ISSUE TITLE
not working instead making even more mess 

### ISSUE THREAD

**Issue by Aeropro4** [lightbeam24/CustomTube#54]
I think its not a bug instead i think idk how to use it cause many people have it working so why not mine and the screenshot of it:
![image](https://github.com/lightbeam24/CustomTube/assets/113044496/835d9f87-5025-4c59-a213-646c82053a5b)

**Comment by lovebirdmic** [comment]
I am having the same issue.

**Comment by lightbeam24** [comment]
You are one of the extremely unlucky few that have this new watch page experiment, I'd estimate only 0.5% or less have it. Given that, as well as the fact that it might just be temporary (kinda like this other experiment a couple months ago), It's far too different from the current watch page to justify fixing fully right now.

I'd recommend using an alternate account, or using YouTube signed out. That's the only way to fully fix it.

**Comment by Aeropro4** [comment]
> You are one of the extremely unlucky few that have this new watch page experiment, I'd estimate only 0.5% or less have it. Given that, as well as the fact that it might just be temporary (kinda like this other experiment a couple months ago), It's far too different from the current watch page to justify fixing fully right now.
> 
> I'd recommend using an alternate account, or using YouTube signed out. That's the only way to fully fix it for now, unfortunately. 

Nah if u are unlucky then just find a way to be lucky like I found my aka found a fix for it

**Comment by lightbeam24** [comment]
> > You are one of the extremely unlucky few that have this new watch page experiment, I'd estimate only 0.5% or less have it. Given that, as well as the fact that it might just be temporary (kinda like this other experiment a couple months ago), It's far too different from the current watch page to justify fixing fully right now.
> > I'd recommend using an alternate account, or using YouTube signed out. That's the only way to fully fix it for now, unfortunately.
> 
> Nah if u are unlucky then just find a way to be lucky like I found my aka found a fix for it

Well that's good if you found a way to fix it.

If this redesign becomes more widespread and it becomes clear that they are rolling this out to everyone now and not later, I will try to make CustomTube compatible with it.

**Comment by Aeropro4** [comment]
> > > You are one of the extremely unlucky few that have this new watch page experiment, I'd estimate only 0.5% or less have it. Given that, as well as the fact that it might just be temporary (kinda like this other experiment a couple months ago), It's far too different from the current watch page to justify fixing fully right now.
> > > I'd recommend using an alternate account, or using YouTube signed out. That's the only way to fully fix it for now, unfortunately.
> > 
> > Nah if u are unlucky then just find a way to be lucky like I found my aka found a fix for it
> 
> Well that's good if you found a way to fix it.
> 
> If this redesign becomes more widespread and it becomes clear that they are rolling this out to everyone now and not later, I will try to make CustomTube compatible with it.

K
