### ISSUE TITLE
Search page is broken (probably very rare)

### ISSUE THREAD

**Issue by elaymm4** [lightbeam24/CustomTube#55]
It seems that I'm one of the few people left that still has older search page style, therefore I'm getting these kind of problems:
![2012](https://github.com/lightbeam24/CustomTube/assets/32716814/dd1b9c19-17c7-4666-b5d4-1f502024e3ec)
![2014](https://github.com/lightbeam24/CustomTube/assets/32716814/c579be7b-5cdd-4b5a-99c7-a8c61f5c485c)
![2019](https://github.com/lightbeam24/CustomTube/assets/32716814/1d1f01aa-edaf-4a01-8a26-cb9f0250ff2f)

**Comment by lightbeam24** [comment]
What old search page style? If you're talking about the old search filters button, I highly doubt that would cause this. Did you test in a Private Window? Do you have any other extensions and/or scripts that affect YouTube enabled? CustomTube is only compatible with uBlock Origin and Return YouTube Dislike right now.

I remember one user had a similar problem with the homepage only showing 1 video per row, and the cause was an old "Sort by Oldest" extension they forgot to uninstall.

**Comment by elaymm4** [comment]
Okay, let me list everything I have ATM:
- 2012 HTML5 Player (Stylus script)
- Disable YouTube AutoPause (Violentmonkey script)
- Return YouTube Comment Username (Violentmonkey script)
- AdBlock
- Annotations Restored for YouTube
- Return YouTube Dislike
- Screenshot YouTube
- YouTube Fix (force loads channel images, since where I live they don't load by default)

Tried disabling every extension and leaving just CustomTube, get same behavior. Tried running it in private window, no changes.
I use Microsoft Edge (Chromium version obviously).

**Comment by lightbeam24** [comment]
Could you try it in Firefox? Try it both signed in and signed out. That should help determine where the issue is coming from.

**Comment by elaymm4** [comment]
Downloaded latest release of Firefox, installed CustomTube from Add-ons page, tested both signed in and signed out. Same results.
![signed-2012](https://github.com/lightbeam24/CustomTube/assets/32716814/7239e878-07df-4d16-957a-918bb6dd9454)
![signed-2014](https://github.com/lightbeam24/CustomTube/assets/32716814/c9f24474-32d6-406b-b3ad-45aafba32342)
![signed-2019](https://github.com/lightbeam24/CustomTube/assets/32716814/fa42924d-7265-4998-8a10-2338f9bea671)
![unsigned-2012](https://github.com/lightbeam24/CustomTube/assets/32716814/0811434f-2969-43f0-a166-c6608a7354fe)
![unsigned-2014](https://github.com/lightbeam24/CustomTube/assets/32716814/d4649e8d-3a7d-4e75-b4b6-d669b8c53378)
![unsigned-2019](https://github.com/lightbeam24/CustomTube/assets/32716814/1c27dea5-831e-44a3-a610-92d96bbcb6c2)

**Comment by lightbeam24** [comment]
Alright, I just looked into it, and you were actually right; the fact that you still have the old Search Filters design is indeed the cause. I'm honestly baffled, I had no idea such a thing could happen. Luckily, the fix is very easy.

Paste this code into Stylus:

```
#header.ytd-search {
  display: none;
}
```

Hopefully this helps.

**Comment by elaymm4** [comment]
Yep, that fixed it!
Thanks for help.
![fixed-2012](https://github.com/lightbeam24/CustomTube/assets/32716814/ab4685eb-a3d6-4056-aec6-7b2a0dc6a959)
![fixed-2014](https://github.com/lightbeam24/CustomTube/assets/32716814/d131e9b6-f3eb-4b25-8094-2aa0e2596ba3)
![fixed-2019](https://github.com/lightbeam24/CustomTube/assets/32716814/a2d0cb6d-fbc3-4c80-8852-9a1c25b01ee7)

**Comment by lightbeam24** [comment]
Good to hear! Just know that once you get the new design, the search filters will be completely invisible, so you'll want to disable that code when that happens.

**Comment by SilverTennyson** [comment]
Please tell me, I have the same problem with the search, what should I do? I didn't understand anything from this topic. (
