### ISSUE TITLE
Volume Button is too small on the players (Auto and 2013-2015 confirmed) (1.2.0 Beta 1)

### ISSUE THREAD

**Issue by gameshowrecaps** [lightbeam24/CustomTube#57]
![image](https://github.com/lightbeam24/CustomTube/assets/57842610/bb3c5c2b-f9e8-456d-8468-90e193951ab2)

**Comment by lightbeam24** [comment]
Yes, player styles are not finished. I plan to fix this for the next beta.

**Comment by lightbeam24** [comment]
Should be fixed in 1.2.0 Beta 2.
