### ISSUE TITLE
Own channel looks off

### ISSUE THREAD

**Issue by gameshowrecaps** [lightbeam24/CustomTube#58]
I've been wanting to report this issue for months and been forgetting to, but here we go:
![image](https://github.com/lightbeam24/CustomTube/assets/57842610/4e243b60-3dcf-4b66-bb6d-3791c106ffb0)

**Comment by lightbeam24** [comment]
I am aware of that. I can't say when it'll be fixed, but I hope to fix it somewhat soon.
