### ISSUE TITLE
rounded tiles at the end of a video, they should be squared

### ISSUE THREAD

**Issue by UnderscoreAngel** [lightbeam24/customtube#6]
![imagen](https://github.com/lightbeam24/customtube/assets/105066360/29c1d3f4-e908-484f-b0d3-fb6156ee40bd)

**Comment by lightbeam24** [comment]
Oh right, I forgot about those. I have "Loop videos by default" enabled so I never see these anymore. If I don't forget, it'll be fixed in the next update.

**Comment by lightbeam24** [comment]
Fixed as of 1.0.3.
