### ISSUE TITLE
Black lines around the player

### ISSUE THREAD

**Issue by daianrgb** [lightbeam24/CustomTube#62]
When you are watching a video using the 2019 theme, you can see some black lines around the video in both the dark theme and the light theme (If I put the video in full screen they disappear)

**Comment by lightbeam24** [comment]
Cannot reproduce. 

Is it just the 2019 layout? Or are other layouts like 2020 or 2017 affected?

Are you using a custom player size? If so which size? (it's 854x480 by default)

What browser are you using? What OS?

Could you possibly send a screenshot?

**Comment by daianrgb** [comment]
I fixed it by re-checking the custom player box and setting it to 1280*720 so I can see the videos in the same size and without the black lines around them.
