### ISSUE TITLE
YouTube description bug (possible new update from YT?)

### ISSUE THREAD

**Issue by gameshowrecaps** [lightbeam24/CustomTube#63]
![image](https://github.com/lightbeam24/CustomTube/assets/57842610/ddabcdab-c532-4f9a-8f19-26849a8979e3)

**Comment by lightbeam24** [comment]
Just submitted 1.1.0.3 which should fix this. Here's the CSS (for Beta users):

```
html[watch-metadata-style] {
  --bt-watch-metadata-desc-min-width: min(450px,100%);
}
```
