### ISSUE TITLE
No video names in history in Late 2009 layout(1.2.0 beta 2

### ISSUE THREAD

**Issue by testreee** [lightbeam24/CustomTube#64]
![image](https://github.com/lightbeam24/CustomTube/assets/93070534/0a19fa1a-1526-4c3e-833e-6a9a358d7ad4)

**Comment by lightbeam24** [comment]
Okay, will look into fixing that for the next beta.

**Comment by lightbeam24** [comment]
Should be fixed in 1.2.0 Beta 3.
