### ISSUE TITLE
(Suggestion) Youtube Annotations

### ISSUE THREAD

**Issue by xxHAKRxx** [lightbeam24/CustomTube#66]
I remember during early YT there was this feature where a creator could put these "annotations" to their videos in the form on a translucent box or speech bubble. These annotations would either add to the video itself or just be random with no context at all. Sometimes you could even click one and it would bring you to another video/website. Is it possible to replicate this today or is it unrestorable?

**Comment by lightbeam24** [comment]
Actually I just found out about another extension that restores annotations very recently:

Github: https://github.com/isaackd/AnnotationsRestored

Firefox: https://addons.mozilla.org/firefox/addon/annotations-restored/

Chrome: https://chrome.google.com/webstore/detail/annotations-restored-for/daabpdmgkghdbfljmeahnplkcldbeefg

I don't think I could implement this into CustomTube though. There's hardly a reason to though, that extension seems to work flawlessly with CustomTube from what I've seen.
