### ISSUE TITLE
When will 1.2.0 update get to Chrome?

### ISSUE THREAD

**Issue by ArbestRiAgain** [lightbeam24/CustomTube#68]
Firefox extension has gotten the update, why not the Chrome extension? Maybe it will be planned to release a bit later?

**Comment by lightbeam24** [comment]
![Screenshot_2023-10-04_22-16-07](https://github.com/lightbeam24/CustomTube/assets/105595945/8a47ea46-3764-4eb9-af73-eecdc379e790)

Pending approval. Firefox approves updates within a few minutes, Chrome takes several hours.
