### ISSUE TITLE
rounded menus 🤮 LOL

### ISSUE THREAD

**Issue by UnderscoreAngel** [lightbeam24/customtube#7]
![imagen](https://github.com/lightbeam24/customtube/assets/105066360/567cc369-58e5-488a-a94c-9ef448b0af1c)
![imagen](https://github.com/lightbeam24/customtube/assets/105066360/4460e234-abf6-4ae7-9f4d-a1b307e1174b)
![imagen](https://github.com/lightbeam24/customtube/assets/105066360/893a5adb-e1b7-4671-adcd-8328006cee68)

**Comment by lightbeam24** [comment]
Yes I'm aware of that. However, I don't think it's worth the effort to fix them unless I'm going to go all the way, and make them as accurate as possible to the way they used to be. I do plan to, but it's a bit lower on the priority list.

**Comment by UnderscoreAngel** [comment]
> Yes I'm aware of that. However, I don't think it's worth the effort to fix them unless I'm going to go all the way, and make them as accurate as possible to the way they used to be. I do plan to, but it's a bit lower on the priority list.
> 
> In other words, I'll fix that, but not right now.

yeah no problem,i could probably do a temp fix and send it here if that helps a bit, i know  how to kill these rounded menus pretty quick

**Comment by lightbeam24** [comment]
That would just be changing the border radius to 0 right? Sure that'd be great, it'd save me the trouble of having to get all the selectors for now.

**Comment by lightbeam24** [comment]
Reddit or Discord I guess, which one sounds better?

**Comment by lightbeam24** [comment]
Fixed as of 1.0.3.
