### ISSUE TITLE
Another possible new YouTube change screwing up channel page

### ISSUE THREAD

**Issue by gameshowrecaps** [lightbeam24/CustomTube#72]
![image](https://github.com/lightbeam24/CustomTube/assets/57842610/42c9f334-6692-4cb7-8ee6-a58507a03831)

**Comment by lightbeam24** [comment]
No, I think it's a faulty update on my part. Will try fixing it later.

**Comment by lightbeam24** [comment]
Should be fixed in 1.2.1.
