### ISSUE TITLE
The 2012 layout progress bar cursor is broken as you can see. it's that small white dot above the progress bar.

### ISSUE THREAD

**Issue by ScratchOSTeam** [lightbeam24/CustomTube#75]
![image](https://github.com/lightbeam24/CustomTube/assets/99697031/d892444a-8447-4689-94bc-db7787f4edde)
![image](https://github.com/lightbeam24/CustomTube/assets/99697031/60967836-f3cc-4a6a-a535-3f2e549c3d16)

**Comment by lightbeam24** [comment]
Does this always happen? Does zooming in and back out again fix it?

**Comment by ScratchOSTeam** [comment]
> Does this always happen? Does zooming in and back out again fix it?

it always happens

**Comment by lightbeam24** [comment]
Do you have any other extensions or scripts enabled? If you were previously using a script to bring back the old player, you should probably disable it. It would also be helpful to know your screen resolution and what browser you're using.

If necessary, open the config window, go to Watch Page, and under Video Player Style, select "Use current player" to disable the old player styling.

**Comment by ScratchOSTeam** [comment]
> Do you have any other extensions or scripts enabled? If you were previously using a script to bring back the old player, you should probably disable it. It would also be helpful to know your screen resolution and what browser you're using.
> 
> If necessary, open the config window, go to Watch Page, and under Video Player Style, select "Use current player" to disable the old player styling.

i found out a progress bar script caused it. it's good now.

**Comment by lightbeam24** [comment]
Alright.
