### ISSUE TITLE
sometimes video data does not update

### ISSUE THREAD

**Issue by UnderscoreAngel** [lightbeam24/customtube#8]
![imagen](https://github.com/lightbeam24/customtube/assets/105066360/333ede51-9aad-42fd-aa49-3194af3e200e)

**Comment by lightbeam24** [comment]
Are you using version 1.0.2?

**Comment by UnderscoreAngel** [comment]
> Are you using version 1.0.2?

Yes, that's the latest version i assume

**Comment by UnderscoreAngel** [comment]
> Yes it is. I made a change to when the metadata decides to update with this version. Perhaps that was the wrong decision. Does it happen often? I haven't had it happen yet.

yes, sometimes it just does not update, it displays a sub count next to the last one, so i guess you could something similar to the "focing comments to load" thing, because i can't think in anything else to fix it

**Comment by lightbeam24** [comment]
I'll have to look into it. Does clicking on another video fix it? (without refreshing the page or opening in a new tab)

**Comment by UnderscoreAngel** [comment]
> I'll have to look into it. Does clicking on another video fix it? (without refreshing the page or opening in a new tab)

yes refreshing/click on other videos fix it

**Comment by lightbeam24** [comment]
Okay, today I've actually been having this happen quite a bit. My internet has been slower than usual today for some reason, so it probably only happens with slower internet, because I was only able to test CustomTube on my own (fast) internet.

I have an idea that might fix this, along with a few other related issues. I plan on trying it out either tomorrow or sometime within the next few days. Hopefully it works.

**Comment by UnderscoreAngel** [comment]
> Okay, today I've actually been having this happen quite a bit. My internet has been slower than usual today for some reason, so it probably only happens with slower internet, because I was only able to test CustomTube on my own (fast) internet.
> 
> I have an idea that might fix this, along with a few other related issues. I plan on trying it out either tomorrow or sometime within the next few days. Hopefully it works.

you can use VMs and rate limit yourself to try and test customtube in other environments and see how it works, but i guess for now it's recommended to use in high speed internet connections, this happened to me over a 10mbps connection (i was using mobile data) meanwhile in my normal 90mbps internet speed worked normally

**Comment by lightbeam24** [comment]
Just released version 1.0.4 which should fix this. Can anyone verify that it's fixed now?

**Comment by lightbeam24** [comment]
Closing the issue, as I'm pretty sure it's fixed now.
