### ISSUE TITLE
Missing changes for "Add a comment" style and the Sort by button in Hitchhiker and possibly other layouts

### ISSUE THREAD

**Issue by ArbestRiAgain** [lightbeam24/CustomTube#82]
YouTube Redux has these changes, example:
<img width="758" alt="Screenshot 2023-10-06 at 10 45 17 PM" src="https://github.com/lightbeam24/CustomTube/assets/132712354/2ee82a1f-45f4-4bae-8534-7e4fb242f71b">

**Comment by lightbeam24** [comment]
Yes, that still needs to be done. Maybe I'll get to it soon, but I can't guarantee it.

**Comment by ArbestRiAgain** [comment]
Latest 1.2.7 version fixed this, closing now
