### ISSUE TITLE
the search page is broken

### ISSUE THREAD

**Issue by REDRUMERRisCOOL** [lightbeam24/CustomTube#84]
screenshot below

![image](https://github.com/lightbeam24/CustomTube/assets/138314570/8dfaa051-7cd7-41e7-94f9-b4da9dbe2367)

**Comment by elaymm4** [comment]
I had similar problem, try this:
https://github.com/lightbeam24/CustomTube/issues/55#issuecomment-1696445084

**Comment by lightbeam24** [comment]
> screenshot below

Does the fix elaymm4 sent work? If so, this fix won't be added to CustomTube since that old search header design is so uncommon now.

**Comment by REDRUMERRisCOOL** [comment]
> > screenshot below
> 
> Does the fix elaymm4 sent work? If so, this fix won't be added to CustomTube since that old search header design is so uncommon now.

it worked thanks for work man
