### ISSUE TITLE
The verified checkmark is in the wrong place

### ISSUE THREAD

**Issue by GemplelyTivadar** [lightbeam24/CustomTube#85]
On channel pages the verified checkmark is under the channel name.
![verified checkmark 1](https://github.com/lightbeam24/CustomTube/assets/95102462/f5a03ad9-846a-4ece-84b2-69c589edf487)

On the watch page it's in the right place, but I think it should be a little bit higher.
![verified checkmark 2](https://github.com/lightbeam24/CustomTube/assets/95102462/9022efe9-1c7a-4f6d-8121-6637208d5380)

**Comment by lightbeam24** [comment]
Yeah I was thinking of fixing that in the next update. Thanks for the reminder.

**Comment by lightbeam24** [comment]
I forgot to mention it in the changelog, but I'm pretty sure this is fixed in 1.2.2.
