### ISSUE TITLE
Profile picture is bigger than the title.

### ISSUE THREAD

**Issue by someoneiguessidkaaaaaaaaaaaaaaaaaa** [lightbeam24/CustomTube#86]
<img width="205" alt="Screenshot 2023-10-07 131530" src="https://github.com/lightbeam24/CustomTube/assets/122063396/6245f788-e4bc-438a-bfc2-ed9678ab67f4">

this happens on the 2008-2009 layouts

**Comment by lightbeam24** [comment]
Do you have any other extensions/scripts enabled? If so, try disabling them.

It would also be worth trying in a private window.

**Comment by someoneiguessidkaaaaaaaaaaaaaaaaaa** [comment]
worked, thanks
