### ISSUE TITLE
YouTube messed up again (potential new update from them)

### ISSUE THREAD

**Issue by gameshowrecaps** [lightbeam24/CustomTube#94]
Can't find the like/dislike button, and the buttons are now messed up.

Edit: This is happening with default settings by the way. I disabled CustomTube and it appears YT did (possibly) another layout update.
![image](https://github.com/lightbeam24/CustomTube/assets/57842610/0a5bf72f-06fc-498c-afdd-e23e3f04c308)

**Comment by lightbeam24** [comment]
Nope, looks like a Return YouTube Dislike issue (tried with CT disabled, dislikes didn't show up). Turn off RYD compatibility and it should work.

**Comment by gameshowrecaps** [comment]
Yep. It's a RYD issue. That seemed to fix it.
