### ISSUE TITLE
Likes and dislike counter overlaid with view counter

### ISSUE THREAD

**Issue by ParkerGit2328** [lightbeam24/CustomTube#95]
![Overlaid counter](https://github.com/lightbeam24/CustomTube/assets/96856359/d7217d22-ea7e-414d-b933-7412a83b32e5)

**Comment by lightbeam24** [comment]
Ooh yeah, looks like it was probably caused by the same layout update that broke Return YouTube Dislike. Might release a fix later today.

**Comment by lightbeam24** [comment]
Should be fixed in 1.2.2.
